<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD9JTksP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD9JTksP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD9JTksP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD9JTksP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD9JTksP\App_KernelDevDebugContainer([
    'container.build_hash' => 'D9JTksP',
    'container.build_id' => '016a2fa4',
    'container.build_time' => 1672846860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD9JTksP');
